### ISSUE TITLE
Current dependency on illuminate/cache is broken with starting at 5.5

### ISSUE THREAD

**Issue by yereth** [userfrosting/cache#1]
The RedisManager construct interface changed and now requires 3 arguments, breaking the userfrosting/cache Redis functionality. Here's a dump of the error:

Fatal error: Uncaught ArgumentCountError: Too few arguments to function Illuminate\Redis\RedisManager::__construct(), 2 passed in /var/www/html/vendor/userfrosting/cache/src/RedisStore.php on line 64 and exactly 3 expected in /var/www/html/vendor/illuminate/redis/RedisManager.php on line 57

**Comment by lcharette** [comment]
I'll lock illuminate version to 5.6 for now. Next version of this package will require 5.7 or better

**Comment by lcharette** [comment]
I think this could actually be properly solved using a try/catch...

**Comment by lcharette** [comment]
There. Now we have a proper fix !

**Comment by yereth** [comment]
Thanks @lcharette for fixing this so fast! I can now simply update to the latest version then?

**Comment by lcharette** [comment]
Yes.
